// Code generated by protoc-gen-go. DO NOT EDIT.
// source: publisher.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Device struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version              string               `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Reference            string               `protobuf:"bytes,3,opt,name=reference,proto3" json:"reference,omitempty"`
	MemoryDump           []byte               `protobuf:"bytes,4,opt,name=memory_dump,json=memoryDump,proto3" json:"memory_dump,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Device) Reset()         { *m = Device{} }
func (m *Device) String() string { return proto.CompactTextString(m) }
func (*Device) ProtoMessage()    {}
func (*Device) Descriptor() ([]byte, []int) {
	return fileDescriptor_publisher_ad773b2b193ef130, []int{0}
}
func (m *Device) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Device.Unmarshal(m, b)
}
func (m *Device) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Device.Marshal(b, m, deterministic)
}
func (dst *Device) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Device.Merge(dst, src)
}
func (m *Device) XXX_Size() int {
	return xxx_messageInfo_Device.Size(m)
}
func (m *Device) XXX_DiscardUnknown() {
	xxx_messageInfo_Device.DiscardUnknown(m)
}

var xxx_messageInfo_Device proto.InternalMessageInfo

func (m *Device) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Device) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Device) GetReference() string {
	if m != nil {
		return m.Reference
	}
	return ""
}

func (m *Device) GetMemoryDump() []byte {
	if m != nil {
		return m.MemoryDump
	}
	return nil
}

func (m *Device) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func init() {
	proto.RegisterType((*Device)(nil), "pb.Device")
}

func init() { proto.RegisterFile("publisher.proto", fileDescriptor_publisher_ad773b2b193ef130) }

var fileDescriptor_publisher_ad773b2b193ef130 = []byte{
	// 197 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x8e, 0x41, 0x4b, 0x80, 0x30,
	0x18, 0x86, 0xd9, 0x2a, 0xc3, 0xcf, 0x28, 0xd8, 0x69, 0x48, 0xa0, 0x74, 0xf2, 0x34, 0xa1, 0x4e,
	0x1d, 0x03, 0x7f, 0x81, 0x74, 0x17, 0xe7, 0x3e, 0x6d, 0xe0, 0xdc, 0x98, 0x9b, 0xd0, 0x7f, 0xea,
	0x47, 0x06, 0x33, 0xe9, 0xf8, 0x3e, 0xef, 0x73, 0x78, 0xe0, 0xc9, 0x45, 0xb9, 0xea, 0xfd, 0x0b,
	0xbd, 0x70, 0xde, 0x06, 0xcb, 0xa8, 0x93, 0x65, 0xb5, 0x58, 0xbb, 0xac, 0xd8, 0x26, 0x22, 0xe3,
	0xdc, 0x06, 0x6d, 0x70, 0x0f, 0xa3, 0x71, 0xa7, 0xf4, 0xf2, 0x43, 0x20, 0xeb, 0xf0, 0xd0, 0x13,
	0xb2, 0x47, 0xa0, 0x5a, 0x71, 0x52, 0x93, 0x26, 0xef, 0xa9, 0x56, 0x8c, 0xc3, 0xfd, 0x81, 0x7e,
	0xd7, 0x76, 0xe3, 0x34, 0xc1, 0x6b, 0xb2, 0x67, 0xc8, 0x3d, 0xce, 0xe8, 0x71, 0x9b, 0x90, 0xdf,
	0xa4, 0xef, 0x1f, 0xb0, 0x0a, 0x0a, 0x83, 0xc6, 0xfa, 0xef, 0x41, 0x45, 0xe3, 0xf8, 0x6d, 0x4d,
	0x9a, 0x87, 0x1e, 0x4e, 0xd4, 0x45, 0xe3, 0xd8, 0x3b, 0xc0, 0xe4, 0x71, 0x0c, 0xa8, 0x86, 0x31,
	0xf0, 0xbb, 0x9a, 0x34, 0xc5, 0x6b, 0x29, 0xce, 0x52, 0x71, 0x95, 0x8a, 0xcf, 0xab, 0xb4, 0xcf,
	0xff, 0xec, 0x8f, 0x20, 0xb3, 0x74, 0xbf, 0xfd, 0x06, 0x00, 0x00, 0xff, 0xff, 0xf8, 0x5f, 0xb4,
	0xc5, 0xed, 0x00, 0x00, 0x00,
}
